# Generated by Django 4.0.5 on 2022-06-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (3, 'Vendor'), (2, 'Consumer')], null=True, verbose_name='User Type'),
        ),
    ]
